In [27]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.feature_selection import RFE
from sklearn.datasets import load_iris
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression

In [28]:
data = pd.DataFrame({
    'Age': [22, 25, None, 30],
    'Salary': [40000, None, 50000, 60000]
})

#using this we can replace the NaN value or empty value with Mean,Median And Mode
imputer = SimpleImputer(strategy='mean')
data[['Age','Salary']] = imputer.fit_transform(data[['Age','Salary']])

print(data)

         Age   Salary
0  22.000000  40000.0
1  25.000000  50000.0
2  25.666667  50000.0
3  30.000000  60000.0


In [29]:
data.sum()  #this statement gives you the table contain null values or not

Age          102.666667
Salary    200000.000000
dtype: float64

In [30]:
#Encoding Catrgorial data with Labeled Encoder
data1 = pd.DataFrame({
    "Names": ["Anjali", "nishant", "vaishnavi", "Swaranjali", "Vaibhavi"],
    #'Salary': [40000, 35656 , 354686 , 50000, 60000]
})

In [31]:
LE = LabelEncoder()

#data1["names_encoded"] = LE.fit_transform(data["Names"])
print(data1)

        Names
0      Anjali
1     nishant
2   vaishnavi
3  Swaranjali
4    Vaibhavi


In [32]:
y = ["spam", "ham", "spam", "ham"]

LE = LabelEncoder()
y_encoded = LE.fit_transform(y)

In [33]:
y_encoded

array([1, 0, 1, 0])

In [34]:
# Encoder with One Hot Encoder 
df = pd.DataFrame({
    "name": ["Anjali", "nishant", "vaishnavi", "Swaranjali", "Vaibhavi"]
})
Enc = OneHotEncoder(sparse_output=False)

result = Enc.fit_transform(df[['name']])  # ✅ double brackets
print(result)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [35]:
iris = load_iris()

In [36]:
X =iris.data
y = iris.target

In [37]:
#1) filter method which starts from 0 features and add up the important features
selector = SelectKBest(score_func=f_classif,k=2)

In [38]:
X_new = selector.fit_transform(X,y)

In [39]:
X_new.shape

(150, 2)

In [40]:
X.shape

(150, 4)

In [41]:
# 2) RFE (Recursive Feature Elimination) which starts from the all features and then removes the less important or the less relevent features

In [42]:
model = LogisticRegression(max_iter=300)

In [43]:
rfe = RFE(model, n_features_to_select=2)

In [44]:
X_rfe = rfe.fit_transform(X,y)

In [45]:
print(rfe.support_)

[False False  True  True]


In [51]:
#handling imbalenced data 
#type:- Oversampling 

sush = load_iris()
X = sush.data
y= sush.target

smote = SMOTE()
X_reshap,y_reshape = smote.fit_resample(X,y)

print(X_reshap)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.